# https://finnian.io/blog/rapid-development-with-node-js-and-docker/

version: '3.1'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    env_file:
      - server/docker.env
  mongo:
    image: mongo
    ports:
      - '27017:27017'